camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    websocket:
      enabled: false
graphiql:
  base-path: /
  mapping: graphiql
